# [START cloudbuild_npm_node]

steps:
# Install dependencies

- name: gcr.io/cloud-builders/gcloud
  args:
  - compute
  - ssh
  - "kashmore-1"
  - --project
  - "kashmore-web"
  - --zone
  - "us-central1-a"
  - --
  - cd /home/jigga_e10 &&
  - sudo apt update &&
  - sudo apt install -y git &&
  - sudo apt install -y nodejs &&
  - sudo apt install -y npm &&
  - sudo apt install -y nginx &&
  - sudo rm -rf kashmore_node &&
  - git clone https://jiggabyte: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@github.com/JiggaByter/kashmore_node.git &&
  - sudo chmod -R +x ./home/jigga_e10/kashmore_node &&
  - cd ./home/jigga_e10/kashmore_node &&
  - sudo cp ./home/jigga_e10/kashmore_node/configs/default /etc/nginx/sites-available/default &&
  - npm install &&
  - npm install -g pm2 &&
  - pm2 stop ./home/jigga_e10/kashmore_node/scripts/serve.sh &&
  - pm2 start ./home/jigga_e10/kashmore_node/scripts/serve.sh &&
  - bash ./home/jigga_e10/kashmore_node/scripts/start.sh

# [END cloudbuild_npm_node] 