# [START cloudbuild_npm_node]
steps:
# Install dependencies
- name: gcr.io/cloud-builders/gcloud
  args:
  - compute
  - ssh
  - "kashmore-1"
  - --project
  - "kashmore-web"
  - --zone
  - "us-central1-a"
  - --ssh-key-file
  - "~/.ssh/google_compute_engine"
  - --
  - sudo apt update &&
  - sudo apt install -y git &&
  - sudo apt install -y nodejs &&
  - sudo apt install -y npm &&
  - sudo apt install -g -y pm2 &&
  - git clone https://github.com/JiggaByter/kashmore_node.git &&
  - cd kashmore_node &&
  - npm install &&
  - pm2 start ./scripts/serve.sh &&
  - bash ./scripts/start.sh

# [END cloudbuild_npm_node]